[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
toju = "CSXnfQsFWxdPB5pnS73TQDA6ivK6kcFnRwtt6TgFquxH"

[programs.testnet]
toju = "CSXnfQsFWxdPB5pnS73TQDA6ivK6kcFnRwtt6TgFquxH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./mainnet-admin-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
