name: Check Unused Dependencies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    name: server - knip!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Run knip
        run: pnpm --filter server knip

  solana-sdk:
    name: solana sdk - knip!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Run knip
        run: pnpm --filter @toju.network/sol knip

  frontend:
    name: ui - knip!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Run knip
        run: pnpm --filter ui knip
