name: Check Unused Dependencies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    name: Server - knip!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'server/pnpm-lock.yaml'
      
      - name: Install dependencies
        run: cd server && pnpm install --no-frozen-lockfile
      
      - name: Run knip
        run: cd server && pnpm knip

  sdk:
    name: sdk - knip!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'sdk/pnpm-lock.yaml'
      
      - name: Install dependencies
        run: cd sdk && pnpm install --no-frozen-lockfile
      
      - name: Run knip
        run: cd sdk && pnpm knip

  frontend:
    name: ui - knip!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'ui/pnpm-lock.yaml'
      
      - name: Install dependencies
        run: cd ui && pnpm install --no-frozen-lockfile
      
      - name: Run knip
        run: cd ui && pnpm knip
